SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "fairroot.gsi.de")
SET(CTEST_DROP_LOCATION "/CDash/submit.php?project=VC")
SET(CTEST_TRIGGER_SITE "fairroot.gsi.de")
SET(CTEST_NIGHTLY_START_TIME "23:00:00 UTC")
SET(CTEST_UPDATE_TYPE "git")

find_program(GITCOMMAND git)
SET(CTEST_UPDATE_COMMAND "${GITCOMMAND}")

mark_as_advanced(GITCOMMAND)
