SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "code.compeng.uni-frankfurt.de")
SET(CTEST_DROP_LOCATION "/dashboard/submit.php?project=Vc")
SET(CTEST_TRIGGER_SITE "${CTEST_DROP_SITE}")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 CET")
SET(CTEST_UPDATE_TYPE "git")

find_program(GITCOMMAND git)
SET(CTEST_UPDATE_COMMAND "${GITCOMMAND}")

mark_as_advanced(GITCOMMAND)
