Set(CTEST_SOURCE_DIRECTORY $ENV{VC_SOURCEDIR})
Set(CTEST_BINARY_DIRECTORY $ENV{VC_BUILDDIR})
Set(CTEST_SITE $ENV{SITE})
Set(CTEST_BUILD_NAME $ENV{LABEL})
Set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
Set(CTEST_PROJECT_NAME "VC")


Set(CTEST_UPDATE_TYPE git)

#Find_Program(GITCOMMAND git)
#Mark_As_Advanced(GITCOMMAND)

Set(CTEST_UPDATE_COMMAND "git")
Set(CTEST_UPDATE_OPTIONS pull)


Set(CTEST_CONFIGURE_COMMAND "${CMAKE_EXECUTABLE_NAME} ${CTEST_SOURCE_DIRECTORY} -DCMAKE_BUILD_TYPE=Release -DBUILD_BENCHMARKS=FALSE")
Set(BUILD_COMMAND "make")
Set(CTEST_BUILD_COMMAND "${BUILD_COMMAND} -j$ENV{number_of_processors}")

#If($ENV{ctest_model} MATCHES Nightly)
  CTEST_EMPTY_BINARY_DIRECTORY(${CTEST_BINARY_DIRECTORY})
#EndIf($ENV{ctest_model} MATCHES Nightly)

CTEST_START ($ENV{ctest_model})
CTEST_UPDATE (SOURCE "${CTEST_SOURCE_DIRECTORY}")
CTEST_CONFIGURE (BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_BUILD (BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_TEST (BUILD "${CTEST_BINARY_DIRECTORY}")
CTEST_SUBMIT ()
